
name = "io_example"
description = "LED Pin i/o example"
version = "1.0.1"

website = "https://sourceforge.net/projects/avr-ada/"
tags = ["avr", "embedded", "demo"]

project-files = ["servo.gpr"]

[configuration.values]
avrada_rts.AVR_MCU = "atmega328p"
avrada_rts.Clock_Frequency = 16000000

[[depends-on]]
gnat_avr_elf = "^11 | ^12.2"
avrada_rts = "^2.0.1"
avrada_mcu = "^2.0.2"
avrada_lib = "^2.0.2"


