/* Configuration for io_example generated by Alire */
#ifndef IO_EXAMPLE_CONFIG_H
#define IO_EXAMPLE_CONFIG_H

#define CRATE_VERSION "1.0.1"
#define CRATE_NAME "io_example"

#define ALIRE_HOST_OS "windows"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "msys2"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
